# Generated by Django 4.1.7 on 2023-03-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_questions_test_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='test',
        ),
    ]
