# Generated by Django 4.1.7 on 2023-03-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_questions_test_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='testing.test'),
        ),
    ]
