# Generated by Django 4.1.7 on 2023-03-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_questions_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('question',)},
        ),
    ]
