# Generated by Django 4.0.2 on 2023-03-12 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=255)),
                ('sex', models.CharField(choices=[('Man', 'M'), ('Women', 'W')], default=None, max_length=255)),
                ('education', models.CharField(choices=[('HighShool', 'highshool'), ('University', 'university'), ('Employee', 'employee')], default=None, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
