# Generated by Django 4.0.2 on 2023-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('HighShool', 'highshool'), ('University', 'university'), ('Employee', 'employee')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('Man', 'M'), ('Women', 'W')], default=None, max_length=255, null=True),
        ),
    ]
