# Generated by Django 4.1.7 on 2023-03-16 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_alter_questions_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
