# Generated by Django 4.0.2 on 2023-03-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_alter_userprofile_education_likes_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_likes', to='testing.test', unique=True),
        ),
    ]
