# Generated by Django 4.1.7 on 2023-03-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_alter_likes_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('test', 'user')},
        ),
    ]
