# Generated by Django 4.1.7 on 2023-03-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0019_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_text',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.test', to_field='title'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.questions', to_field='question_text')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='other1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='other2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='other3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='right',
        ),
    ]
