# Generated by Django 4.1.7 on 2023-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0020_alter_questions_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer_text')},
        ),
    ]
