# Generated by Django 4.1.7 on 2023-04-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0024_alter_score_score_viewscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='views_count',
        ),
    ]
