# Generated by Django 4.1.7 on 2023-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0028_alter_answer_options_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
