# Generated by Django 4.1.7 on 2023-04-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0029_alter_answer_answer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer_text')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_id',
        ),
    ]
