# Generated by Django 4.1.7 on 2023-04-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0030_alter_answer_options_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['answer_id']},
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
