# Generated by Django 4.1.7 on 2023-04-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0031_alter_answer_options_answer_answer_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'answer_text', 'answer_id')},
        ),
    ]
