# Generated by Django 4.1.7 on 2023-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0032_alter_answer_unique_together_alter_answer_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('test', 'question_text', 'question_id')},
        ),
    ]
